### ISSUE TITLE
Can this code reproduce the result in the paper?

### ISSUE THREAD

**Issue by lixiaoyu0575** [hsd1503/MINA#3]
Thanks for your impressive work in the paper.
I follow the instruction is readme and the result looks like below. The auprc is also getting lower and lower. I wonder what is going wrong?

loss  0.40022895
train | auc : 0.43219060662917214 |auprc : 2.975607816708485e-06 |
mat : [[394651      0]
 [ 37591      0]] |

**Comment by hsd1503** [comment]
Hi, thanks for your interest! I just tested the code and it works well on my machine. I guess your problem comes from the data preprocessing part, since I recently updated that from matlab to python, the code your used might be an intermediate version (sorry for this). Would you please update the code now and have a try again? Please let me know if you have further questions. Thanks!

**Comment by hsd1503** [comment]
I'm closing this issue, feel free to reopen it.
